# Generated by Django 4.0.2 on 2022-07-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apsaras', '0003_tag_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rate', models.SmallIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsaras.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsaras.product')),
            ],
            options={
                'abstract': False,
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
